#!/usr/bin/env python3
"""
sample_reranker_train_tiles.py — Document the deterministic 600-tile
training-set sample used by the CNN reranker.

**Authoritative source: `phase30/train_sample_seed42.txt`** (checked
into git).  That file is the exact stem list used to train the 0.515
reranker ensemble and is what should be passed to
`benchmark.py --tiles-file`.

This script is for two purposes:
  1. Validate that every stem in the authoritative file is actually
     eligible (exists in raw/, has >=5 cat=2 GTs, isn't in val/).
  2. Provide a documented seed=42 sampling procedure for anyone who
     wants to regenerate a similar 600-tile sample from scratch.

Note: the historical 600-tile set was generated by two separate seed=42
calls — `random.sample(candidates, 300)` followed by a fresh
`random.shuffle` + take-next-300 — so reproducing it bit-exact from a
single-pass shuffle is not possible.  The single-pass procedure here
yields a different deterministic 600 tiles with the same statistical
properties.  For reproducing the published 0.515 result, ALWAYS use the
checked-in file rather than re-running this script.

Sampling rules (the historical procedure):
  * Source: every tile in data/tcd/images/data/tcd/raw/.
  * Exclude any tile stem that exists in the holdout (val/).
  * Require >=5 cat=2 tree GTs per tile.
  * Sample (random.sample + random.shuffle, both seed=42) to 600 stems.
"""
import json, random, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "phase30"))
from benchmark import _parse_coco_annotations  # noqa: E402

RAW_DIR     = REPO / "data" / "tcd" / "images" / "data" / "tcd" / "raw"
HOLDOUT_DIR = REPO / "data" / "tcd" / "images" / "data" / "tcd" / "val"
OUT_PATH    = REPO / "phase30" / "train_sample_seed42.txt"
N_SAMPLE    = 600
MIN_TREES   = 5
SEED        = 42


def _eligible_candidates():
    val_stems = {p.name.replace("_meta.json", "")
                 for p in HOLDOUT_DIR.glob("*_meta.json")}
    candidates = []
    for m in sorted(RAW_DIR.glob("*_meta.json")):
        stem = m.name.replace("_meta.json", "")
        if stem in val_stems:
            continue
        try:
            meta = json.load(open(m))
        except Exception:
            continue
        n_tree = sum(1 for cat, *_ in _parse_coco_annotations(meta) if cat == 2)
        if n_tree >= MIN_TREES:
            candidates.append(stem)
    return val_stems, candidates


def validate():
    """Confirm every stem in the authoritative file is eligible."""
    if not OUT_PATH.exists():
        print(f"❌ Missing authoritative file: {OUT_PATH}")
        return False
    with open(OUT_PATH) as f:
        listed = [s.strip() for s in f if s.strip()]
    val_stems, candidates = _eligible_candidates()
    cand_set = set(candidates)
    bad = [s for s in listed if s not in cand_set]
    in_holdout = [s for s in listed if s in val_stems]
    print(f"Listed in {OUT_PATH.name}: {len(listed)} stems")
    print(f"Ineligible (missing / <{MIN_TREES} GTs): {len(bad)}")
    print(f"In holdout (should be 0): {len(in_holdout)}")
    if bad or in_holdout:
        for s in bad[:5]:
            print(f"  bad: {s}")
        for s in in_holdout[:5]:
            print(f"  in holdout: {s}")
        return False
    print("✅ All stems valid.")
    return True


def regenerate():
    """Produce a fresh seed=42 600-tile sample.  NOT bit-exact with the
    authoritative file (see module docstring) — use only when the
    authoritative file is genuinely lost."""
    random.seed(SEED)
    _, candidates = _eligible_candidates()
    print(f"Eligible train tiles (>={MIN_TREES} cat=2 GTs): {len(candidates)}")
    random.shuffle(candidates)
    sample = sorted(candidates[:N_SAMPLE])
    print(f"Sampled {len(sample)} tiles with seed={SEED} (single-pass).")
    print(f"⚠  This will NOT match the historical authoritative file.")
    out_alt = OUT_PATH.with_suffix(".regenerated.txt")
    with open(out_alt, "w") as f:
        for stem in sample:
            f.write(stem + "\n")
    print(f"Wrote {out_alt}")


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--regenerate", action="store_true",
                    help="Write a fresh seed=42 sample (different from the "
                         "historical file).  Default is to validate only.")
    args = ap.parse_args()
    if args.regenerate:
        regenerate()
    else:
        ok = validate()
        sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
